tpcx_bb/queries/q03/tpcx_bb_query_03.py, tpcx_bb/queries/q11/tpcx_bb_query_11.py, tpcx_bb/queries/q22/tpcx_bb_query_22.py, tpcx_bb/queries/q25/tpcx_bb_query_25.py, tpcx_bb/queries/q26/tpcx_bb_query_26.py, tpcx_bb/xbb_tools/text_vectorizers/dist_hashing_vectorizer.py
This PR:
- Updates all calls to `rmm.device_array` to use `numba.cuda.device_array`, as we're phasing out the RMM wrapper. See https://github.com/rapidsai/rmm/issues/180 for the discussion about phasing out `rmm.device_array`
We should also define a single `convert_datestring_to_days` function and import it within each query. This can be done in a follow-up PR.
=> [REVIEW] Switch rmm.device_array to numba.cuda.device_array

tpcx_bb/queries/q21/tpcx_bb_query_21_sql.py
Remove unused imports
Add strip() function to the `i_item_desc` column
=> [REVIEW] BlazingSQL 21: Using strip() to i_item_desc column

tpcx_bb/queries/q18/tpcx_bb_query_18_sql.py
This PR:
- Switches BSQL Q18 to assume the sentiment text files are in the data directory, and grab them from the configuration.
This closes #81
=> [REVIEW] Use config for q18 bsql sentiment path

tpcx_bb/queries/q18/tpcx_bb_query_18_sql.py
Instead of using `.tolist()` method it is being replaced by `to_arrow().to_pylist()`  methods. As the error message advice
`TypeError: cuDF does not support conversion to host memory via tolist() method. Consider using .to_arrow().to_pylist() to construct a Python list.`
=> [REVIEW] BlazingSQL Q18: Using to_arrow().to_pylist() instead of deprecate to_list() method

README.md, tpcx_bb/xbb_tools/cluster_startup.py
This PR adds some useful parameters for BlazingSQL.
* MAX_KERNEL_RUN_THREADS
* MAX_NUM_ORDER_BY_PARTITIONS_PER_NODE
* ORDER_BY_SAMPLES_RATIO
* NUM_BYTES_PER_ORDER_BY_PARTITION
=> [REVIEW] Add more BlazingSQL useful params

tpcx_bb/queries/q18/tpcx_bb_query_18.py, tpcx_bb/queries/q18/tpcx_bb_query_18_sql.py
This PR:
- Simplifies the passing of `targets` between function calls, but does not fully resolve the need to send `targets` via PyArrow from the client process.
Without using the CPU list, we get index alignment issues. These can be triaged in a follow-up (along with some refactoring).
Passing correctness checks at SF1K:
```
python tpcx_bb_query_18.py --config_file=../../benchmark_runner/benchmark_config.yaml
Using default arguments
Connected to ucx://172.22.1.26:8786
...
Sentiment Analysis Query
95.80851052730421% overlap with 1533536 rows (RAPIDS denominator)
95.90632204766145% overlap with 1531972 rows (Spark denominator)
Correctness Assertion True
...
python tpcx_bb_query_18_sql.py --config_file=../../benchmark_runner/benchmark_config.yaml
Using default arguments
Connected to …
```
=> [REVIEW] Remove q18 tolist method and partial cleanup of targets handling

tpcx_bb/queries/q08/tpcx_bb_query_08_sql.py
This PR avoids  `MemoryError: std::bad_alloc: CUDA error at: /home/christianc/conda/envs/bsql-tpcx/include/rmm/mr/device/cuda_memory_resource.hpp68: cudaErrorMemoryAllocation out of memory` at sf 10K
Just tested at sf **1K** on the **dgx201**. Took 21 s
```
(bsql-tpcx-bb) christianc@rl-dgx2-d17-u05-rapids-dgx201:~/tpcx-bb/tpcx_bb/queries/q08$ python tpcx_bb_query_08_sql.py --config_file=/home/christianc/yaml_dir/validation_1k_config.yaml
Using default arguments
Connected to tcp://10.150.162.27:8786
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/christianc/miniconda3/envs/bsql-tpcx-bb/lib/blazingsql-algebra.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the …
```
=> [REVIEW] BlazinqSQL q08: using ORDER BY to distribute better the data

tpcx_bb/queries/q28/tpcx_bb_query_28_sql.py
This PR uses `bc.partition()` statement instead of `ORDER BY`. For now we have detect a sort of issue when using ORDER BY that in  a future we will handle better.
More details:   https://github.com/BlazingDB/blazingsql/blob/branch-0.15/pyblazing/pyblazing/apiv2/context.py#L2102
=> [REVIEW] BlazingSQL q28: Using bc.partition() instead of ORDER BY

tpcx_bb/queries/q02/tpcx_bb_query_02_sql.py
This PR add a couple of `CAST()` for both `wcs_user_sk` & `wcs_item_sk` columns in the first SQL statement. Also deletes both    `wcs_result` & `session_df`  ` dask_cudf.DataFrames` after create the `session_df` table. Finally, removes the constant column called `item_sk_2` from the last SQL statement.
=> [REVIEW] BlazingSQL 02: Apply CAST to the first SQL

tpcx_bb/benchmark_runner.py
This PR:
- Fixes a bug in the benchmark runner's `load_query` function that makes it hard coded to pure dask queries
=> [REVIEW] Use the filename passed into load_query for file loading

tpcx_bb/queries/q01/tpcx_bb_query_01_sql.py, tpcx_bb/queries/q02/tpcx_bb_query_02_sql.py, tpcx_bb/queries/q03/tpcx_bb_query_03_sql.py, tpcx_bb/queries/q04/tpcx_bb_query_04_sql.py, tpcx_bb/queries/q08/tpcx_bb_query_08_sql.py, tpcx_bb/queries/q10/tpcx_bb_query_10_sql.py, tpcx_bb/queries/q13/tpcx_bb_query_13_sql.py, tpcx_bb/queries/q18/tpcx_bb_query_18_sql.py, tpcx_bb/queries/q19/tpcx_bb_query_19_sql.py, tpcx_bb/queries/q23/tpcx_bb_query_23_sql.py, tpcx_bb/queries/q27/tpcx_bb_query_27_sql.py, tpcx_bb/queries/q29/tpcx_bb_query_29_sql.py, tpcx_bb/queries/q30/tpcx_bb_query_30_sql.py
This PR adds a `persist()` call just before` bc.create_table()` when the table comes from `dask_cudf.dataFrame` . As well, call to the `bc.drop_table()` function respectively for those tables that were created from a` dask_cudf.DataFrame`.
Additional:  
Q03: 
* Remove  `i.i_category_id` from the first SQL statement (unused)
* Adds a `CAST` to the `COALESCE()` from the first SQL statement
=> [REVIEW] Persist() and bc.drop_table() functions when source is a dask_cudf.DataFrame

tpcx_bb/queries/q10/tpcx_bb_query_10_sql.py, tpcx_bb/queries/q18/tpcx_bb_query_18_sql.py, tpcx_bb/queries/q19/tpcx_bb_query_19_sql.py, tpcx_bb/xbb_tools/cluster_startup.py
This PR update some BlazingSQL params as add some others. 
This PR also avoid the use of `bc.partition()` , instead of that uses `ORDER BY` statement. As well, add a couple of `del`s  after drop tables. Finally add a line of code ( `config["protocol"] = str(url)[0:3]` ) just for tracking protocool.
Tested at sf **1K** on the **dgx201**
```
(bsql-tpcx) christianc@rl-dgx2-d17-u05-rapids-dgx201:~/tpcx-bb/tpcx_bb$ python benchmark_runner.py --config_file=/home/christianc/yaml_dir/benchmark_1k_w_validation.yaml 
['10', '18', '19']
Using default arguments
Connected to tcp://10.150.162.27:8786
BlazingContext ready
Blazing Queries
10
/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/cudf/core/column/string.py:700: UserWarning: `n` parameter is not supported when `pat` and …
```
=> [REVIEW] Update blazing params, add ORDER BY instead of bc.partition() for q10, q18 and q19

tpcx_bb/queries/q02/tpcx_bb_query_02_sql.py
This PR just remove `ORDER BY tstamp_inSec` as it is not necessary.
=> [REVIEW] BlazingSQL: Q02 - Remove ORDER BY tstamp

tpcx_bb/queries/q03/tpcx_bb_query_03.py
`os.path.join` is always better than `+` for making a path.
=> Use os.path.join() to concatenate directory parts for Query 3 

tpcx_bb/queries/q18/tpcx_bb_query_18.py, tpcx_bb/queries/q18/tpcx_bb_query_18_sql.py
This PR:
- Updates q18 to use the DataFrame constructor instead of `from_gpu_matrix` to convert a cupy array into a DataFrame
Verified correct at SF1K.
This closes https://github.com/rapidsai/tpcx-bb/issues/18
=> [REVIEW] Use DataFrame constructor to convert cupy arrays into dataframes

tpcx_bb/xbb_tools/cluster_startup.py
This PR:
- Updates the gathering of worker gpu memory from the scheduler for distributed 2.30. It's now directly exposed as an integer, rather than a list.
This closes https://github.com/rapidsai/tpcx-bb/issues/113
=> [REVIEW] Update accessing of gpu memory from scheduler for distributed 2.30

tpcx_bb/queries/q02/tpcx_bb_query_02.py, tpcx_bb/queries/q03/tpcx_bb_query_03.py, tpcx_bb/queries/q04/tpcx_bb_query_04.py, tpcx_bb/queries/q08/tpcx_bb_query_08.py, tpcx_bb/queries/q08/tpcx_bb_query_08_sql.py, tpcx_bb/queries/q16/tpcx_bb_query_16.py, tpcx_bb/queries/q20/tpcx_bb_query_20.py, tpcx_bb/queries/q22/tpcx_bb_query_22.py, tpcx_bb/queries/q25/tpcx_bb_query_25.py, tpcx_bb/queries/q26/tpcx_bb_query_26.py, tpcx_bb/queries/q29/tpcx_bb_query_29.py, tpcx_bb/queries/q30/tpcx_bb_query_30.py, tpcx_bb/xbb_tools/merge_util.py, tpcx_bb/xbb_tools/utils.py
This PR:
- Switches all hash repartitions to use the `df.shuffle` API
- Updates dask queries that are now failing due to upstream changes
- Updates the clustering query labels check to ignore the index, which is immaterial but misaligned due to the dask-cudf reader vs dask.dataframe
This closes #112, closes #115, and closes #117 
All queries verified at SF1K
=> [REVIEW] Switch hash repartition to shuffle API and fix dask incorrect dask queries due to upstream changes

conda/rapids-tpcx-bb.yml
This PR:
- Avoids the issue in https://github.com/rapidsai/tpcx-bb/issues/121 by pinning to known working commits for Dask and Distributed
=> [REVIEW] Pin to known working dask/distributed commits with rapids 0.16

tpcx_bb/xbb_tools/cluster_startup.py
This PR adds three BSQL params:
`MAX_ORDER_BY_SAMPLES_PER_NODE`: The max number order by samples to capture per node.
default: 10000
`TRANSPORT_POOL_NUM_BUFFERS`: The number of buffers in the punned buffer memory pool.
default: 100 buffers
`MAX_JOIN_SCATTER_MEM_OVERHEAD`: The bigger this value, the more  likely one of the tables of join will be scattered to all  the nodes, instead of doing a standard hash based partitioning shuffle. Value is in bytes.
default: 500000000
To read about these, and other parameters, check: https://docs.blazingdb.com/docs/config_options
=> [REVIEW] Adding more BSQL params

tpcx_bb/queries/load_test/tpcx_bb_load_test.py
This PR:
- Fixes the logic error in the load test script's handling of the `web_clickstreams` table
- Updates the argument parser to be consistent with the queries; this was left out as an oversight during a refactor
Tested this just now converting the raw SF1K CSV tables (data + data_refresh) to 3GB parquet files on a DGX-1 with 32GB V100s in a fresh conda environment made from the tpcx-bb.yml in the repository.
This closes https://github.com/rapidsai/tpcx-bb/issues/123
=> [REVIEW] Fix logic and update load test script

README.md, tpcx_bb/cluster_configuration/cluster-startup.sh
This PR:
- Updates the default cluster communication to be TCP while https://github.com/rapidsai/tpcx-bb/issues/126 is unresolved
- Updates the relevant portion of the README
=> [REVIEW] Default cluster to TCP

tpcx_bb/xbb_tools/cluster_startup.py
BlazingSQL is broken: https://github.com/BlazingDB/blazingsql/issues/1037
This workaround allows the repo to work when BlazingSQL isn't enabled.
=> Only import BlazingSQL as necessary

tpcx_bb/queries/q05/tpcx_bb_query_05.py
This PR:
- Removes a `reset_index(drop=True)` call on a Series that goes down the `__setitem__` codepath. This causes index alignment issues with the new(ish) `__dask_null_index__` that is generated in the data coming from our parquet writer scripts.
Verified correct without the reset index, so it's likely that it only is in the code due to an old bug in index handling that has since been resolved.
This closes #133
=> [REVIEW] Remove q05 reset_index call that causes failures with dask null index

conda/rapids-tpcx-bb.yml
This PR:
- Unpins dask and distributed from the default conda environment
- Removes nightly pytorch from the default environment, as we are not using it by default
- Also removes a redundant blazingsql channel
=> [REVIEW] Unpin dask/distributed and remove nightly pytorch default environment

conda/rapids-tpcx-bb.yml
This PR:
- Updates the BSQL conda channel to not use an explicit label
This closes https://github.com/rapidsai/gpu-bdb/issues/141
=> [REVIEW] Update bsql conda to use the main channel

conda/rapids-tpcx-bb.yml, tpcx_bb/benchmark_runner/slurm/rapids-tpcx-bb-cuda11.yml
This PR:
- Uses the stable dask and distributed in the default conda environments due to the ongoing scheduler work
=> [REVIEW] Use stable release of dask and distributed

conda/rapids-tpcx-bb.yml
30/30 TCP queries succeed at SF1K in the 2020-12-11 nightlies.
This closes https://github.com/rapidsai/gpu-bdb/issues/156
=> Use cupy 8

tpcx_bb/xbb_tools/cluster_startup.py
This PR:
- Sets RMM as the memory resource for cupy allocations
Imports are happening inside the scope of the `attach_to_cluster` function to avoid any potential ordering issues related to which library first touches the CUDA driver (not sure this is necessary, but have seen some odd behavior).
=> Use rmm for all cupy allocations in client and worker processes

tpcx_bb/xbb_tools/cluster_startup.py
This PR removes the `ORDER_BY_SAMPLES_RATIO` `config_option` as was removed from `BlazingSQL`, also add a new one called `PROTOCOL` which by default is defined as `AUTO`.  To have more context about this parameter, please check it out this merged PR https://github.com/BlazingDB/blazingsql/pull/1285.
=> [REVIEW] Updating config_option: add PROTOCOL, remove ORDER_BY_SAMPLES_RATIO

tpcx_bb/queries/q28/tpcx_bb_query_28_sql.py
This PR closes #151 for now setting up the `ORDER_BY_SAMPLES_RATIO` value to` 0.002`  to the second `sql`. `ORDER BY` will be re-factorized in a future.  It shows **Correctness Assertion True** at sf 1K
```
Accuracy: 0.9984961971138552
Precision: 0.9971834870532952
Confusion Matrix: [[5.20660e+04 1.30000e+01 1.91000e+02]
[6.20000e+01 3.54210e+04 1.30000e+02]
[2.07000e+02 7.30000e+01 3.61364e+05]]
/home/christianc/miniconda3/envs/bsql-tpcx/lib/python3.7/site-packages/cudf/core/column/string.py:731: UserWarning: `n` parameter is not supported when `pat` and `repl` are list-like inputs
"`n` parameter is not supported when "
Supervised Learning Query
Precisiom delta percent: 2.7047481485066505
AUC delta percent: 2.839950503852733
Precision higher/similar: True
AUC higher/similar: True …
```
=> [REVIEW] BlazingSQL Q28 - Remove bc.partition(), using ORDER BY

README.md
This PR:
1. Makes explicit in the README that gpu-bdb is derived from and not comparable to tpcx-bb itself.
2. Directory, module, and filename changes in the README text are reflections of proposed changes to the actual gpu-bdb code to come in followup PRs.
=> [REVIEW] README scrub

gpu_bdb/bdb_tools/cluster_startup.py
This PR set up default values for `TRANSPORT_BUFFER_BYTE_SIZE` and `TRANSPORT_POOL_NUM_BUFFERS`  as they were recently updated -> https://github.com/BlazingDB/blazingsql/blob/branch-0.18/pyblazing/pyblazing/apiv2/context.py#L1392-L1395
=> [REVIEW] Updating TRANSPORT default values

gpu_bdb/benchmark_runner/slurm/run.sh
This PR:
- Cleans up `slurm/run.sh` and correctly uses `spawn-workers.sh`
=> Use spawn-workers and cleanup run.sh

gpu_bdb/benchmark_runner/slurm/run.sh
This PR:
- Works around srun to get the scheduler/client job id and use that as a dependency for the worker job.
We should eventually switch to using sbatch which will let us use the --parsable option to capture the scheduler/client node job id.
=> Enforce slurm worker job dependency on scheduler job

gpu_bdb/benchmark_runner/slurm/run.sh, gpu_bdb/benchmark_runner/slurm/spawn-workers.sh
This PR:
- Defaults the partition to Slurm backfill, adds a job name for the worker job, and adds a sleep to handle simultaneous allocations
=> Slurm backfill updates

conda/rapids-gpu-bdb.yml, gpu_bdb/benchmark_runner/slurm/rapids-gpu-bdb-cuda11.yml
This PR:
- Pins spacy to 2.3 in the conda environments.
This closes https://github.com/rapidsai/gpu-bdb/issues/188
=> Pin spacy to 2.3

gpu_bdb/bdb_tools/cupy_metrics.py, gpu_bdb/queries/q05/gpu_bdb_query_05.py, gpu_bdb/queries/q05/gpu_bdb_query_05_sql.py
This PR:
- Rips out the custom confusion matrix utility and uses `cuml.metrics.confusion_matrix`
- Verified correct
See https://github.com/rapidsai/cuml/issues/3567 for the need to explicitly cast to int32. After that issue is resolved, we can update this.
=> switch cupy_conf_mat to confusion_matrix

gpu_bdb/bdb_tools/sessionization.py, gpu_bdb/queries/q08/gpu_bdb_query_08.py, gpu_bdb/queries/q08/gpu_bdb_query_08_sql.py
This PR:
- Adds a `fillna` op after the `diff` calls in sessionization. We use these to create masks for filtering, so they are filled with True or False as appropriate based on the query logic
- Also removes a redundant diff() call and column `time_delta`
This closes https://github.com/rapidsai/gpu-bdb/issues/195
=> Use fillna in sessionization to account for updated cudf null handling in binaryops

gpu_bdb/queries/q10/gpu_bdb_query_10_sql.py, gpu_bdb/queries/q18/gpu_bdb_query_18_sql.py, gpu_bdb/queries/q19/gpu_bdb_query_19_sql.py
This PR closes #201 .
It add the `file_format` parameter when creating tables that comes from sentiment files  (`.txt` format in these cases)
=> [REVIEW] Add file_format parameter for the sentiment files

gpu_bdb/benchmark_runner/slurm/Dockerfile, gpu_bdb/benchmark_runner/slurm/rapids-gpu-bdb-cuda11.yml
This PR:
- Updates the Slurm Dockerfile and associated conda environment for the RAPIDS 0.19 release (0.20 nightlies)
- Upgrades MOFED to 5.2-2.2.0.0 and UCX to branch 1.9
=> Slurm Dockerfile updates

gpu_bdb/bdb_tools/utils.py
Closes #214 .
Marking the input as explicit user entered resolves the issue.
=> fix gspread handling of strings with leading digits

gpu_bdb/bdb_tools/q05_utils.py, gpu_bdb/bdb_tools/q18_utils.py
Updates the use of `to_array` in query 05 since it was deprecated.
Updates the use of `find_multiple` in q18 since it now returns a list column instead of a host array (previous behavior).
=> Update use of deprecated api for 22.04

gpu_bdb/bdb_tools/utils.py
Currently, gpu-bdb only generates profiles for the `read_tables` and `main` functions. This means that when there are tasks that are created within  those functions, but not computed until the `write_result` function they don't show up in any profiles. This is why some queries like dask-sql query 14 generate completely empty profiles and other dask-sql queries generate incomplete profiles.
This PR unifies profile generation such that the entirety of the query run is encompassed in a single profile (now called `profile.html`). This way, all tasks executed within the `read_tables`, `main`, or `write_result` functions will be included in a single profile.
=> [WIP] Unify profile generation to include entirety of query run

gpu_bdb/bdb_tools/q01_utils.py, gpu_bdb/bdb_tools/q06_utils.py, gpu_bdb/bdb_tools/q07_utils.py, gpu_bdb/bdb_tools/q09_utils.py, gpu_bdb/bdb_tools/q11_utils.py, gpu_bdb/bdb_tools/q12_utils.py, gpu_bdb/bdb_tools/q13_utils.py, gpu_bdb/bdb_tools/q14_utils.py, gpu_bdb/bdb_tools/q15_utils.py, gpu_bdb/bdb_tools/q16_utils.py, gpu_bdb/bdb_tools/q17_utils.py, gpu_bdb/bdb_tools/q20_utils.py, gpu_bdb/bdb_tools/q21_utils.py, gpu_bdb/bdb_tools/q22_utils.py, gpu_bdb/bdb_tools/q24_utils.py, gpu_bdb/bdb_tools/q29_utils.py, gpu_bdb/bdb_tools/readers.py, gpu_bdb/bdb_tools/utils.py, gpu_bdb/benchmark_runner/benchmark_config.yaml, gpu_bdb/queries/q11/gpu_bdb_query_11_dask_sql.py, gpu_bdb/queries/q16/gpu_bdb_query_16_dask_sql.py
Fixes #230 
All of the queries (01, 06, 07, 09 11, 12,13,14,15,16,17,20,21, 23, 24, 29) run successfully except for q22. However, once that is up and running, I'll commit the changes here.
=> [WIP] Adding pure SQL GPU-BDB Queries

gpu_bdb/bdb_tools/q25_utils.py, gpu_bdb/bdb_tools/q26_utils.py, gpu_bdb/bdb_tools/q30_utils.py, gpu_bdb/queries/q25/gpu_bdb_query_25_dask_sql.py, gpu_bdb/queries/q26/gpu_bdb_query_26_dask_sql.py
Reverts rapidsai/gpu-bdb#241
We should revert the changes pushed in this PR as : 
1. Q25 and Q26 changes are buggy and introduce the following error.  
```python
Traceback (most recent call last):
File "/datasets/vjawa/miniconda3/envs/rapids-gpu-bdb-dask-sql-feb-11/lib/python3.8/site-packages/bdb_tools/utils.py", line 334, in run_sql_query
results = benchmark(
File "/datasets/vjawa/miniconda3/envs/rapids-gpu-bdb-dask-sql-feb-11/lib/python3.8/site-packages/bdb_tools/utils.py", line 57, in benchmark
result = func(*args, **kwargs)
File "gpu_bdb_query_25_dask_sql.py", line 188, in main
results_dict = get_clusters(client=client, ml_input_df=cluster_input_ddf)
File "gpu_bdb_query_25_dask_sql.py", line 58, in get_clusters
pd.DataFrame(results_dict["cid_labels"]), npartitions=output.npartitions …
```
=> Revert "Adding queries 25, 26 and 30 to be reviewed"

gpu_bdb/bdb_tools/utils.py
This fixes an issue where results files have incorrect names when the `output_directory` configuration option is left blank. For example,  without this fix, query 10 writes its results to `Noneq10-results.parquet` instead of `q10-results.parquet`.
Closes #260
=> Fix result writing

conda/rapids-gpu-bdb-dask-sql-cuda11.2.yml
This PR removes a duplicate occurrence of `oauth2client` in yml file.
=> Remove a duplicate entry in yml file

gpu_bdb/cluster_configuration/cluster-startup-slurm.sh
Specifying GPU<->IB mapping should not be needed with newer versions of
Dask and UCX. This change simplifies the launching process.
=> Update Slurm scripts for IB
